default['mailserver']['recipient_delimiter'] = '.'
default['mailserver']['database']['user'] = 'mailuser'
#default['mailserver']['database']['password'] = set it on the recipe, with a random value
default['mailserver']['database']['hosts'] = '127.0.0.1'
default['mailserver']['database']['dbname'] = 'mailserver'
default['mailserver']['storage_size'] = 10
default['mailserver']['storage_root'] = '/var/spool/mail'
default['mailserver']['storage_path'] = "#{node['mailserver']['storage_root']}/vhosts"
default['mailserver']['vmail_user'] = 'vmail'
default['mailserver']['vmail_group'] = 'vmail'
