default['mailserver']['recipient_delimiter'] = '.'
default['mailserver']['ssl_cipher_list'] = 'EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH+aRSA+RC4:EECDH:EDH+aRSA:RC4:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS'
default['mailserver']['database']['user'] = 'mailuser'
#default['mailserver']['database']['password'] = set it on the recipe, with a random value
default['mailserver']['database']['hosts'] = '127.0.0.1'
default['mailserver']['database']['dbname'] = 'mailserver'
default['mailserver']['cert']['cert'] = "/etc/pki/tls/certs/#{node['fqdn']}.pem"
default['mailserver']['cert']['key'] = "/etc/pki/tls/private/#{node['fqdn']}.pem"
default['mailserver']['storage_size'] = 20
default['mailserver']['storage_root'] = '/var/spool/mail'
default['mailserver']['storage_path'] = "#{node['mailserver']['storage_root']}/vhosts"
default['mailserver']['vmail_user'] = 'vmail'
default['mailserver']['vmail_group'] = 'vmail'
